### ISSUE TITLE
User debian-transmission is not created on restore script

### ISSUE THREAD

**Issue by Krakinou** [YunoHost-Apps/transmission_ynh#57]
Restoring transmission does not work. 
Log from the restore:
```
51938 DEBUG + chown -R debian-transmission:www-data /home/yunohost.transmission/
52092 ERROR Impossible de restaurer l’application « transmission »
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/backup.py", line 1302, in _restore_app
    env=env_dict)
  File "/usr/lib/moulinette/yunohost/hook.py", line 390, in hook_exec
    raise YunohostError('hook_exec_failed', path=path)
YunohostError: Échec de l’exécution du script « /tmp/restoreJ8KKJX/restore »
```

**Comment by Krakinou** [comment]
as a matter of fact, the same issue occurs when I try to install tranmission:
```
2019-05-01 14:53:53,076: DEBUG - + mkdir -p /home/yunohost.transmission/progress /home/yunohost.transmission/completed /home/yunohost.transmission/watched
2019-05-01 14:53:53,076: WARNING - chown: utilisateur incorrect: « debian-transmission:www-data »
2019-05-01 14:53:53,078: DEBUG - + chown -R debian-transmission:www-data /home/yunohost.transmission/
2019-05-01 14:53:53,079: WARNING - !!
2019-05-01 14:53:53,080: DEBUG - + ynh_exit_properly
2019-05-01 14:53:53,081: WARNING -   transmission's script has encountered an error. Its execution was cancelled.
2019-05-01 14:53:53,083: DEBUG - + local exit_code=1
```

**Comment by Krakinou** [comment]
Manually run 
````
apt remove transmission-*
````
And then retry to install : this time it worked. Maybe an issue with the dependencies?

**Comment by alexAubin** [comment]
That sounds similar to https://github.com/YunoHost-Apps/transmission_ynh/issues/44 and https://github.com/YunoHost-Apps/transmission_ynh/pull/52

If i'm not mistaking, this user is supposed to be created via transmission-common but there are weird issues related to this package (stuff it's supposed to do mysteriously disappears)

Forcing the reinstall of this specific package usually solves the issue ...
